const mockProductsList = [
    {
        id: 1,
        name: 'Smartphone',
        cost: 499.99,
        type: 'Electronics',
    },
    {
        id: 2,
        name: 'Laptop',
        cost: 899.99,
        type: 'Electronics',
    },
    {
        id: 3,
        name: 'T-Shirt',
        cost: 19.99,
        type: 'Clothing',
    },
    {
        id: 4,
        name: 'Coffee Maker',
        cost: 59.99,
        type: 'Home and Kitchen',
    },
    {
        id: 5,
        name: 'Toy Robot',
        cost: 29.99,
        type: 'Toys',
    },
    {
        id: 6,
        name: 'Shampoo',
        cost: 7.99,
        type: 'Beauty',
    },
    {
        id: 7,
        name: 'Tablet',
        cost: 299.99,
        type: 'Electronics',
    },
    {
        id: 8,
        name: 'Dress Shirt',
        cost: 24.99,
        type: 'Clothing',
    },
    {
        id: 9,
        name: 'Blender',
        cost: 39.99,
        type: 'Home and Kitchen',
    },
    {
        id: 10,
        name: 'Action Figure',
        cost: 14.99,
        type: 'Toys',
    },
    {
        id: 11,
        name: 'Lipstick',
        cost: 9.99,
        type: 'Beauty',
    },
    {
        id: 12,
        name: 'Digital Camera',
        cost: 199.99,
        type: 'Electronics',
    },
    {
        id: 13,
        name: 'Jeans',
        cost: 39.99,
        type: 'Clothing',
    },
    {
        id: 14,
        name: 'Microwave Oven',
        cost: 79.99,
        type: 'Home and Kitchen',
    },
    {
        id: 15,
        name: 'Board Game',
        cost: 29.99,
        type: 'Toys',
    },
    {
        id: 16,
        name: 'Face Cream',
        cost: 12.99,
        type: 'Beauty',
    },
    {
        id: 17,
        name: 'Headphones',
        cost: 49.99,
        type: 'Electronics',
    },
    {
        id: 18,
        name: 'Sweater',
        cost: 34.99,
        type: 'Clothing',
    },
    {
        id: 19,
        name: 'Coffee Grinder',
        cost: 19.99,
        type: 'Home and Kitchen',
    },
    {
        id: 20,
        name: 'Remote Control Car',
        cost: 17.99,
        type: 'Toys',
    },
    {
        id: 21,
        name: 'Perfume',
        cost: 59.99,
        type: 'Beauty',
    },
    {
        id: 22,
        name: 'Smartwatch',
        cost: 149.99,
        type: 'Electronics',
    },
    {
        id: 23,
        name: 'Dress',
        cost: 44.99,
        type: 'Clothing',
    },
    {
        id: 24,
        name: 'Toaster',
        cost: 29.99,
        type: 'Home and Kitchen',
    },
    {
        id: 25,
        name: 'Building Blocks',
        cost: 24.99,
        type: 'Toys',
    },
    {
        id: 26,
        name: 'Lip Balm',
        cost: 4.99,
        type: 'Beauty',
    },
    {
        id: 27,
        name: 'Digital TV',
        cost: 349.99,
        type: 'Electronics',
    },
    {
        id: 28,
        name: 'Sneakers',
        cost: 69.99,
        type: 'Clothing',
    },
    {
        id: 29,
        name: 'Waffle Maker',
        cost: 29.99,
        type: 'Home and Kitchen',
    },
    {
        id: 30,
        name: 'Remote Control Helicopter',
        cost: 39.99,
        type: 'Toys',
    },
];

export default mockProductsList;
